language: node_js
node_js:
- '8'
branchs:
  only:
  - master
addons:
  ssh_known_hosts: "$host_ip"
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_5474e3bfcbd3_key -iv $encrypted_5474e3bfcbd3_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- npm config set registry https://registry.npm.taobao.org --global
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host $host_ip\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install
script:
- npm run build
after_success:
- rsync -rav --delete ./dist/ "$host_username@$host_ip:$host_path"
